server:
  port: 8761 #포트번호 지정

spring:
  application:
    name: EurekaDiscoveryServer # 서비스 ID
  cloud:
    config:
      uri: http://localhost:8888

eureka:
  client:
    register-with-eureka: false # default : true
    fetch-registry: false # default : true